import type { Viewport } from 'next';
import '@/app/styles/globals.css';
import { CookieProvider } from './modules/CookiesProvider/CookiesComponent';
import Providers from './modules/providers';

/*
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};
*/

export const viewport: Viewport = {
    width: 'device-width',
    initialScale: 0.9
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <CookieProvider>
            <Providers>{children}</Providers>
        </CookieProvider>
    );
}

